"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](bg1)\
$os\
[█](bg:bg2 fg:bg1)\
$directory\
[](bg:bg3 fg:bg2)\
$git_branch\
$git_status\
[ ](fg:bg3)\
$line_break
\n$character
"""

palette = 'everforest'

[line_break]
disabled = true

[os]
disabled = false
style = "bg:bg1 fg:primary"
format = "[$symbol ]($style)"

[os.symbols]
Arch = "󰣇"

[directory]
style = "bg:bg2 fg:primary"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Dev" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:bg3 fg:primary"
format = '[[ $symbol $branch ]($style)]($style)'

[git_status]
style = "bg:bg3 fg:primary"
format = '[[($all_status$ahead_behind )]($style)]($style)'

[character]
success_symbol = '[❯](bold fg:bg3)'
error_symbol = '[❯](bold fg:bg3)'
vimcmd_symbol = '[❮](bold fg:bg3)'
vimcmd_replace_one_symbol = '[❮](bold fg:prompt)'
vimcmd_replace_symbol = '[❮](bold fg:prompt)'
vimcmd_visual_symbol = '[❮](bold fg:primary)'

[palettes.ristretto]
bg1 = "#1f0e04"
bg2 = "#431307"
bg3 = "#932C0D"
primary = "#FCE4BE"
prompt = "#ED7B35"

[palettes.everforest]
bg1 = "#83c092"
bg2 = "#a7c080"
bg3 = "#d3c6aa"
primary = "#475258"
prompt = "#7fbbb3"
